### ISSUE TITLE
more homologs

### ISSUE THREAD

**Issue by felbecker** [rcedgar/balifam#2]
Hi,

thank you for compiling the 3 versions. 

Do you have an automated script to download the homologs from Pfam or can you give a protocol of how you gathered them (search and selection criteria)? Since Pfam families are constantly growing, do you think it might be possible to scale up to 100k or larger? Redundancy doesn't really matter. I think interesting things could happen to state-of-the-art aligners at 100k and beyond. Things that you might not see for 10k.

**Comment by rcedgar** [comment]
Sorry, I don't have a script, it was actually a quite complicated pipeline that needed some hand-holding. But you can leverage the trimmed alignments that I made, e.g. make an HMM from the Balibase subset of the Balifam reference alignment (i.e., as truncated to the domain) and use this HMM to search large protein databases (e.g. NCBI NR), this would generate large sets. This would add large numbers of homologs.
